/*
 * Siren.
 *
 * Documentation of our Siren API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Alert struct {
	Annotations *Annotations `json:"annotations,omitempty"`
	Labels *Labels `json:"labels,omitempty"`
	Status string `json:"status,omitempty"`
}
