/*
 * Siren.
 *
 * Documentation of our Siren API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client
import (
	"time"
)

type Rule struct {
	CreatedAt time.Time `json:"CreatedAt,omitempty"`
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	Entity string `json:"entity,omitempty"`
	GroupName string `json:"group_name,omitempty"`
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Namespace string `json:"namespace,omitempty"`
	Status string `json:"status,omitempty"`
	Template string `json:"template,omitempty"`
	Variables []RuleVariable `json:"variables,omitempty"`
}
