/*
 * Siren.
 *
 * Documentation of our Siren API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type Labels struct {
	Severity string `json:"severity,omitempty"`
}
