// Code generated by mockery 2.9.4. DO NOT EDIT.

package subscription

import (
	alertmanager "github.com/odpf/siren/pkg/subscription/alertmanager"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

// SyncConfig provides a mock function with given fields: _a0, _a1
func (_m *ClientMock) SyncConfig(_a0 alertmanager.AMConfig, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(alertmanager.AMConfig, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
