// Code generated by mockery v2.10.0. DO NOT EDIT.

package receiver

import (
	mock "github.com/stretchr/testify/mock"

	slack "github.com/odpf/siren/plugins/receivers/slack"
)

// MockSlackService is an autogenerated mock type for the slackService type
type MockSlackService struct {
	mock.Mock
}

// GetWorkspaceChannels provides a mock function with given fields: _a0
func (_m *MockSlackService) GetWorkspaceChannels(_a0 string) ([]slack.Channel, error) {
	ret := _m.Called(_a0)

	var r0 []slack.Channel
	if rf, ok := ret.Get(0).(func(string) []slack.Channel); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]slack.Channel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
