DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS rules;
DROP TABLE IF EXISTS templates;
DROP TABLE IF EXISTS receivers;
DROP TABLE IF EXISTS namespaces;
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS providers;