// Code generated by mockery 2.9.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/odpf/siren/domain"
	mock "github.com/stretchr/testify/mock"
)

// NamespaceService is an autogenerated mock type for the NamespaceService type
type NamespaceService struct {
	mock.Mock
}

// CreateNamespace provides a mock function with given fields: _a0
func (_m *NamespaceService) CreateNamespace(_a0 *domain.Namespace) (*domain.Namespace, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Namespace
	if rf, ok := ret.Get(0).(func(*domain.Namespace) *domain.Namespace); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Namespace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Namespace) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteNamespace provides a mock function with given fields: _a0
func (_m *NamespaceService) DeleteNamespace(_a0 uint64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNamespace provides a mock function with given fields: _a0
func (_m *NamespaceService) GetNamespace(_a0 uint64) (*domain.Namespace, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Namespace
	if rf, ok := ret.Get(0).(func(uint64) *domain.Namespace); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Namespace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListNamespaces provides a mock function with given fields:
func (_m *NamespaceService) ListNamespaces() ([]*domain.Namespace, error) {
	ret := _m.Called()

	var r0 []*domain.Namespace
	if rf, ok := ret.Get(0).(func() []*domain.Namespace); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Namespace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Migrate provides a mock function with given fields:
func (_m *NamespaceService) Migrate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateNamespace provides a mock function with given fields: _a0
func (_m *NamespaceService) UpdateNamespace(_a0 *domain.Namespace) (*domain.Namespace, error) {
	ret := _m.Called(_a0)

	var r0 *domain.Namespace
	if rf, ok := ret.Get(0).(func(*domain.Namespace) *domain.Namespace); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Namespace)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.Namespace) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
