// Code generated by mockery v2.12.2. DO NOT EDIT.

package mocks

import (
	receiver "github.com/odpf/siren/core/receiver"
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// ReceiverService is an autogenerated mock type for the ReceiverService type
type ReceiverService struct {
	mock.Mock
}

type ReceiverService_Expecter struct {
	mock *mock.Mock
}

func (_m *ReceiverService) EXPECT() *ReceiverService_Expecter {
	return &ReceiverService_Expecter{mock: &_m.Mock}
}

// CreateReceiver provides a mock function with given fields: _a0
func (_m *ReceiverService) CreateReceiver(_a0 *receiver.Receiver) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*receiver.Receiver) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiverService_CreateReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReceiver'
type ReceiverService_CreateReceiver_Call struct {
	*mock.Call
}

// CreateReceiver is a helper method to define mock.On call
//  - _a0 *receiver.Receiver
func (_e *ReceiverService_Expecter) CreateReceiver(_a0 interface{}) *ReceiverService_CreateReceiver_Call {
	return &ReceiverService_CreateReceiver_Call{Call: _e.mock.On("CreateReceiver", _a0)}
}

func (_c *ReceiverService_CreateReceiver_Call) Run(run func(_a0 *receiver.Receiver)) *ReceiverService_CreateReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*receiver.Receiver))
	})
	return _c
}

func (_c *ReceiverService_CreateReceiver_Call) Return(_a0 error) *ReceiverService_CreateReceiver_Call {
	_c.Call.Return(_a0)
	return _c
}

// DeleteReceiver provides a mock function with given fields: _a0
func (_m *ReceiverService) DeleteReceiver(_a0 uint64) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiverService_DeleteReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReceiver'
type ReceiverService_DeleteReceiver_Call struct {
	*mock.Call
}

// DeleteReceiver is a helper method to define mock.On call
//  - _a0 uint64
func (_e *ReceiverService_Expecter) DeleteReceiver(_a0 interface{}) *ReceiverService_DeleteReceiver_Call {
	return &ReceiverService_DeleteReceiver_Call{Call: _e.mock.On("DeleteReceiver", _a0)}
}

func (_c *ReceiverService_DeleteReceiver_Call) Run(run func(_a0 uint64)) *ReceiverService_DeleteReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ReceiverService_DeleteReceiver_Call) Return(_a0 error) *ReceiverService_DeleteReceiver_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetReceiver provides a mock function with given fields: _a0
func (_m *ReceiverService) GetReceiver(_a0 uint64) (*receiver.Receiver, error) {
	ret := _m.Called(_a0)

	var r0 *receiver.Receiver
	if rf, ok := ret.Get(0).(func(uint64) *receiver.Receiver); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*receiver.Receiver)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiverService_GetReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReceiver'
type ReceiverService_GetReceiver_Call struct {
	*mock.Call
}

// GetReceiver is a helper method to define mock.On call
//  - _a0 uint64
func (_e *ReceiverService_Expecter) GetReceiver(_a0 interface{}) *ReceiverService_GetReceiver_Call {
	return &ReceiverService_GetReceiver_Call{Call: _e.mock.On("GetReceiver", _a0)}
}

func (_c *ReceiverService_GetReceiver_Call) Run(run func(_a0 uint64)) *ReceiverService_GetReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *ReceiverService_GetReceiver_Call) Return(_a0 *receiver.Receiver, _a1 error) *ReceiverService_GetReceiver_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListReceivers provides a mock function with given fields:
func (_m *ReceiverService) ListReceivers() ([]*receiver.Receiver, error) {
	ret := _m.Called()

	var r0 []*receiver.Receiver
	if rf, ok := ret.Get(0).(func() []*receiver.Receiver); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*receiver.Receiver)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReceiverService_ListReceivers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReceivers'
type ReceiverService_ListReceivers_Call struct {
	*mock.Call
}

// ListReceivers is a helper method to define mock.On call
func (_e *ReceiverService_Expecter) ListReceivers() *ReceiverService_ListReceivers_Call {
	return &ReceiverService_ListReceivers_Call{Call: _e.mock.On("ListReceivers")}
}

func (_c *ReceiverService_ListReceivers_Call) Run(run func()) *ReceiverService_ListReceivers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReceiverService_ListReceivers_Call) Return(_a0 []*receiver.Receiver, _a1 error) *ReceiverService_ListReceivers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Migrate provides a mock function with given fields:
func (_m *ReceiverService) Migrate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiverService_Migrate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrate'
type ReceiverService_Migrate_Call struct {
	*mock.Call
}

// Migrate is a helper method to define mock.On call
func (_e *ReceiverService_Expecter) Migrate() *ReceiverService_Migrate_Call {
	return &ReceiverService_Migrate_Call{Call: _e.mock.On("Migrate")}
}

func (_c *ReceiverService_Migrate_Call) Run(run func()) *ReceiverService_Migrate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReceiverService_Migrate_Call) Return(_a0 error) *ReceiverService_Migrate_Call {
	_c.Call.Return(_a0)
	return _c
}

// NotifyReceiver provides a mock function with given fields: rcv, payloadMessage
func (_m *ReceiverService) NotifyReceiver(rcv *receiver.Receiver, payloadMessage receiver.NotificationMessage) error {
	ret := _m.Called(rcv, payloadMessage)

	var r0 error
	if rf, ok := ret.Get(0).(func(*receiver.Receiver, receiver.NotificationMessage) error); ok {
		r0 = rf(rcv, payloadMessage)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiverService_NotifyReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyReceiver'
type ReceiverService_NotifyReceiver_Call struct {
	*mock.Call
}

// NotifyReceiver is a helper method to define mock.On call
//  - rcv *receiver.Receiver
//  - payloadMessage receiver.NotificationMessage
func (_e *ReceiverService_Expecter) NotifyReceiver(rcv interface{}, payloadMessage interface{}) *ReceiverService_NotifyReceiver_Call {
	return &ReceiverService_NotifyReceiver_Call{Call: _e.mock.On("NotifyReceiver", rcv, payloadMessage)}
}

func (_c *ReceiverService_NotifyReceiver_Call) Run(run func(rcv *receiver.Receiver, payloadMessage receiver.NotificationMessage)) *ReceiverService_NotifyReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*receiver.Receiver), args[1].(receiver.NotificationMessage))
	})
	return _c
}

func (_c *ReceiverService_NotifyReceiver_Call) Return(_a0 error) *ReceiverService_NotifyReceiver_Call {
	_c.Call.Return(_a0)
	return _c
}

// UpdateReceiver provides a mock function with given fields: _a0
func (_m *ReceiverService) UpdateReceiver(_a0 *receiver.Receiver) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*receiver.Receiver) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReceiverService_UpdateReceiver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReceiver'
type ReceiverService_UpdateReceiver_Call struct {
	*mock.Call
}

// UpdateReceiver is a helper method to define mock.On call
//  - _a0 *receiver.Receiver
func (_e *ReceiverService_Expecter) UpdateReceiver(_a0 interface{}) *ReceiverService_UpdateReceiver_Call {
	return &ReceiverService_UpdateReceiver_Call{Call: _e.mock.On("UpdateReceiver", _a0)}
}

func (_c *ReceiverService_UpdateReceiver_Call) Run(run func(_a0 *receiver.Receiver)) *ReceiverService_UpdateReceiver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*receiver.Receiver))
	})
	return _c
}

func (_c *ReceiverService_UpdateReceiver_Call) Return(_a0 error) *ReceiverService_UpdateReceiver_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewReceiverService creates a new instance of ReceiverService. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewReceiverService(t testing.TB) *ReceiverService {
	mock := &ReceiverService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
