// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	notification "github.com/raystack/siren/core/notification"
	mock "github.com/stretchr/testify/mock"

	queues "github.com/raystack/siren/plugins/queues"
)

// Queuer is an autogenerated mock type for the Queuer type
type Queuer struct {
	mock.Mock
}

type Queuer_Expecter struct {
	mock *mock.Mock
}

func (_m *Queuer) EXPECT() *Queuer_Expecter {
	return &Queuer_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: ctx, filter
func (_m *Queuer) Cleanup(ctx context.Context, filter queues.FilterCleanup) error {
	ret := _m.Called(ctx, filter)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, queues.FilterCleanup) error); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type Queuer_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
//   - filter queues.FilterCleanup
func (_e *Queuer_Expecter) Cleanup(ctx interface{}, filter interface{}) *Queuer_Cleanup_Call {
	return &Queuer_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx, filter)}
}

func (_c *Queuer_Cleanup_Call) Run(run func(ctx context.Context, filter queues.FilterCleanup)) *Queuer_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queues.FilterCleanup))
	})
	return _c
}

func (_c *Queuer_Cleanup_Call) Return(_a0 error) *Queuer_Cleanup_Call {
	_c.Call.Return(_a0)
	return _c
}

// Dequeue provides a mock function with given fields: ctx, receiverTypes, batchSize, handlerFn
func (_m *Queuer) Dequeue(ctx context.Context, receiverTypes []string, batchSize int, handlerFn func(context.Context, []notification.Message) error) error {
	ret := _m.Called(ctx, receiverTypes, batchSize, handlerFn)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, int, func(context.Context, []notification.Message) error) error); ok {
		r0 = rf(ctx, receiverTypes, batchSize, handlerFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type Queuer_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - receiverTypes []string
//   - batchSize int
//   - handlerFn func(context.Context , []notification.Message) error
func (_e *Queuer_Expecter) Dequeue(ctx interface{}, receiverTypes interface{}, batchSize interface{}, handlerFn interface{}) *Queuer_Dequeue_Call {
	return &Queuer_Dequeue_Call{Call: _e.mock.On("Dequeue", ctx, receiverTypes, batchSize, handlerFn)}
}

func (_c *Queuer_Dequeue_Call) Run(run func(ctx context.Context, receiverTypes []string, batchSize int, handlerFn func(context.Context, []notification.Message) error)) *Queuer_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(int), args[3].(func(context.Context, []notification.Message) error))
	})
	return _c
}

func (_c *Queuer_Dequeue_Call) Return(_a0 error) *Queuer_Dequeue_Call {
	_c.Call.Return(_a0)
	return _c
}

// Enqueue provides a mock function with given fields: ctx, ms
func (_m *Queuer) Enqueue(ctx context.Context, ms ...notification.Message) error {
	_va := make([]interface{}, len(ms))
	for _i := range ms {
		_va[_i] = ms[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...notification.Message) error); ok {
		r0 = rf(ctx, ms...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type Queuer_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - ms ...notification.Message
func (_e *Queuer_Expecter) Enqueue(ctx interface{}, ms ...interface{}) *Queuer_Enqueue_Call {
	return &Queuer_Enqueue_Call{Call: _e.mock.On("Enqueue",
		append([]interface{}{ctx}, ms...)...)}
}

func (_c *Queuer_Enqueue_Call) Run(run func(ctx context.Context, ms ...notification.Message)) *Queuer_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]notification.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(notification.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *Queuer_Enqueue_Call) Return(_a0 error) *Queuer_Enqueue_Call {
	_c.Call.Return(_a0)
	return _c
}

// ErrorCallback provides a mock function with given fields: ctx, ms
func (_m *Queuer) ErrorCallback(ctx context.Context, ms notification.Message) error {
	ret := _m.Called(ctx, ms)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, notification.Message) error); ok {
		r0 = rf(ctx, ms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_ErrorCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorCallback'
type Queuer_ErrorCallback_Call struct {
	*mock.Call
}

// ErrorCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - ms notification.Message
func (_e *Queuer_Expecter) ErrorCallback(ctx interface{}, ms interface{}) *Queuer_ErrorCallback_Call {
	return &Queuer_ErrorCallback_Call{Call: _e.mock.On("ErrorCallback", ctx, ms)}
}

func (_c *Queuer_ErrorCallback_Call) Run(run func(ctx context.Context, ms notification.Message)) *Queuer_ErrorCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(notification.Message))
	})
	return _c
}

func (_c *Queuer_ErrorCallback_Call) Return(_a0 error) *Queuer_ErrorCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

// Stop provides a mock function with given fields: ctx
func (_m *Queuer) Stop(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Queuer_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Queuer_Expecter) Stop(ctx interface{}) *Queuer_Stop_Call {
	return &Queuer_Stop_Call{Call: _e.mock.On("Stop", ctx)}
}

func (_c *Queuer_Stop_Call) Run(run func(ctx context.Context)) *Queuer_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Queuer_Stop_Call) Return(_a0 error) *Queuer_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

// SuccessCallback provides a mock function with given fields: ctx, ms
func (_m *Queuer) SuccessCallback(ctx context.Context, ms notification.Message) error {
	ret := _m.Called(ctx, ms)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, notification.Message) error); ok {
		r0 = rf(ctx, ms)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Queuer_SuccessCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SuccessCallback'
type Queuer_SuccessCallback_Call struct {
	*mock.Call
}

// SuccessCallback is a helper method to define mock.On call
//   - ctx context.Context
//   - ms notification.Message
func (_e *Queuer_Expecter) SuccessCallback(ctx interface{}, ms interface{}) *Queuer_SuccessCallback_Call {
	return &Queuer_SuccessCallback_Call{Call: _e.mock.On("SuccessCallback", ctx, ms)}
}

func (_c *Queuer_SuccessCallback_Call) Run(run func(ctx context.Context, ms notification.Message)) *Queuer_SuccessCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(notification.Message))
	})
	return _c
}

func (_c *Queuer_SuccessCallback_Call) Return(_a0 error) *Queuer_SuccessCallback_Call {
	_c.Call.Return(_a0)
	return _c
}

// Type provides a mock function with given fields:
func (_m *Queuer) Type() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Queuer_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type Queuer_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *Queuer_Expecter) Type() *Queuer_Type_Call {
	return &Queuer_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *Queuer_Type_Call) Run(run func()) *Queuer_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Queuer_Type_Call) Return(_a0 string) *Queuer_Type_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewQueuer interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueuer creates a new instance of Queuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueuer(t mockConstructorTestingTNewQueuer) *Queuer {
	mock := &Queuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
