// Code generated by mockery 2.9.0. DO NOT EDIT.

package codeexchange

import (
	mock "github.com/stretchr/testify/mock"
)

// MockExchangeRepository is an autogenerated mock type for the MockExchangeRepository type
type MockExchangeRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *MockExchangeRepository) Get(_a0 string) (string, error) {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Migrate provides a mock function with given fields:
func (_m *MockExchangeRepository) Migrate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: _a0
func (_m *MockExchangeRepository) Upsert(_a0 *AccessToken) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*AccessToken) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
