// Code generated by mockery v2.6.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/odpf/siren/client"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// TemplatesAPICaller is an autogenerated mock type for the TemplatesAPICaller type
type TemplatesAPICaller struct {
	mock.Mock
}

// CreateTemplateRequest provides a mock function with given fields: ctx, localVarOptionals
func (_m *TemplatesAPICaller) CreateTemplateRequest(ctx context.Context, localVarOptionals *client.TemplatesApiCreateTemplateRequestOpts) (client.Template, *http.Response, error) {
	ret := _m.Called(ctx, localVarOptionals)

	var r0 client.Template
	if rf, ok := ret.Get(0).(func(context.Context, *client.TemplatesApiCreateTemplateRequestOpts) client.Template); ok {
		r0 = rf(ctx, localVarOptionals)
	} else {
		r0 = ret.Get(0).(client.Template)
	}

	var r1 *http.Response
	if rf, ok := ret.Get(1).(func(context.Context, *client.TemplatesApiCreateTemplateRequestOpts) *http.Response); ok {
		r1 = rf(ctx, localVarOptionals)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *client.TemplatesApiCreateTemplateRequestOpts) error); ok {
		r2 = rf(ctx, localVarOptionals)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
