// Code generated by mockery 2.9.0. DO NOT EDIT.

package slacknotifier

import "github.com/stretchr/testify/mock"

// MockSlackNotifier is an autogenerated mock type for the SlackNotifier type
type MockSlackNotifier struct {
	mock.Mock
}

// Notify provides a mock function with given fields: _a0, _a1
func (_m *MockSlackNotifier) Notify(_a0 *SlackMessage, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(*SlackMessage, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
