// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	slack "github.com/slack-go/slack"
)

// GoSlackCaller is an autogenerated mock type for the GoSlackCaller type
type GoSlackCaller struct {
	mock.Mock
}

type GoSlackCaller_Expecter struct {
	mock *mock.Mock
}

func (_m *GoSlackCaller) EXPECT() *GoSlackCaller_Expecter {
	return &GoSlackCaller_Expecter{mock: &_m.Mock}
}

// GetConversationsForUserContext provides a mock function with given fields: ctx, params
func (_m *GoSlackCaller) GetConversationsForUserContext(ctx context.Context, params *slack.GetConversationsForUserParameters) ([]slack.Channel, string, error) {
	ret := _m.Called(ctx, params)

	var r0 []slack.Channel
	if rf, ok := ret.Get(0).(func(context.Context, *slack.GetConversationsForUserParameters) []slack.Channel); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]slack.Channel)
		}
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, *slack.GetConversationsForUserParameters) string); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, *slack.GetConversationsForUserParameters) error); ok {
		r2 = rf(ctx, params)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GoSlackCaller_GetConversationsForUserContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConversationsForUserContext'
type GoSlackCaller_GetConversationsForUserContext_Call struct {
	*mock.Call
}

// GetConversationsForUserContext is a helper method to define mock.On call
//  - ctx context.Context
//  - params *slack.GetConversationsForUserParameters
func (_e *GoSlackCaller_Expecter) GetConversationsForUserContext(ctx interface{}, params interface{}) *GoSlackCaller_GetConversationsForUserContext_Call {
	return &GoSlackCaller_GetConversationsForUserContext_Call{Call: _e.mock.On("GetConversationsForUserContext", ctx, params)}
}

func (_c *GoSlackCaller_GetConversationsForUserContext_Call) Run(run func(ctx context.Context, params *slack.GetConversationsForUserParameters)) *GoSlackCaller_GetConversationsForUserContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*slack.GetConversationsForUserParameters))
	})
	return _c
}

func (_c *GoSlackCaller_GetConversationsForUserContext_Call) Return(channels []slack.Channel, nextCursor string, err error) *GoSlackCaller_GetConversationsForUserContext_Call {
	_c.Call.Return(channels, nextCursor, err)
	return _c
}

// GetUserByEmailContext provides a mock function with given fields: ctx, email
func (_m *GoSlackCaller) GetUserByEmailContext(ctx context.Context, email string) (*slack.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *slack.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *slack.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slack.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GoSlackCaller_GetUserByEmailContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmailContext'
type GoSlackCaller_GetUserByEmailContext_Call struct {
	*mock.Call
}

// GetUserByEmailContext is a helper method to define mock.On call
//  - ctx context.Context
//  - email string
func (_e *GoSlackCaller_Expecter) GetUserByEmailContext(ctx interface{}, email interface{}) *GoSlackCaller_GetUserByEmailContext_Call {
	return &GoSlackCaller_GetUserByEmailContext_Call{Call: _e.mock.On("GetUserByEmailContext", ctx, email)}
}

func (_c *GoSlackCaller_GetUserByEmailContext_Call) Run(run func(ctx context.Context, email string)) *GoSlackCaller_GetUserByEmailContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *GoSlackCaller_GetUserByEmailContext_Call) Return(_a0 *slack.User, _a1 error) *GoSlackCaller_GetUserByEmailContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// SendMessageContext provides a mock function with given fields: ctx, channel, options
func (_m *GoSlackCaller) SendMessageContext(ctx context.Context, channel string, options ...slack.MsgOption) (string, string, string, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, channel)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, ...slack.MsgOption) string); ok {
		r0 = rf(ctx, channel, options...)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(context.Context, string, ...slack.MsgOption) string); ok {
		r1 = rf(ctx, channel, options...)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 string
	if rf, ok := ret.Get(2).(func(context.Context, string, ...slack.MsgOption) string); ok {
		r2 = rf(ctx, channel, options...)
	} else {
		r2 = ret.Get(2).(string)
	}

	var r3 error
	if rf, ok := ret.Get(3).(func(context.Context, string, ...slack.MsgOption) error); ok {
		r3 = rf(ctx, channel, options...)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GoSlackCaller_SendMessageContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessageContext'
type GoSlackCaller_SendMessageContext_Call struct {
	*mock.Call
}

// SendMessageContext is a helper method to define mock.On call
//  - ctx context.Context
//  - channel string
//  - options ...slack.MsgOption
func (_e *GoSlackCaller_Expecter) SendMessageContext(ctx interface{}, channel interface{}, options ...interface{}) *GoSlackCaller_SendMessageContext_Call {
	return &GoSlackCaller_SendMessageContext_Call{Call: _e.mock.On("SendMessageContext",
		append([]interface{}{ctx, channel}, options...)...)}
}

func (_c *GoSlackCaller_SendMessageContext_Call) Run(run func(ctx context.Context, channel string, options ...slack.MsgOption)) *GoSlackCaller_SendMessageContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]slack.MsgOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(slack.MsgOption)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *GoSlackCaller_SendMessageContext_Call) Return(_a0 string, _a1 string, _a2 string, _a3 error) *GoSlackCaller_SendMessageContext_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

type mockConstructorTestingTNewGoSlackCaller interface {
	mock.TestingT
	Cleanup(func())
}

// NewGoSlackCaller creates a new instance of GoSlackCaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewGoSlackCaller(t mockConstructorTestingTNewGoSlackCaller) *GoSlackCaller {
	mock := &GoSlackCaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
